#!/bin/bash
sudo wget -qO- https://experimental.docker.com/ | sh
sudo usermod -aG docker $USER
sudo chown -R $USER /usr/local/bin
curl -L https://github.com/docker/machine/releases/download/v0.8.0-rc1/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && chmod +x /usr/local/bin/docker-machine
curl -L https://github.com/docker/compose/releases/download/1.8.0-rc1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-115.0.0-linux-x86_64.tar.gz
tar xvf google-cloud-sdk-115.0.0-linux-x86_64.tar.gz
cd google-cloud-sdk
./install.sh